// ============================================================
// Factory Compiler — Migration Generator
// Input:  EntitySchemaMeta[] (플러그인 매니페스트에서)
// Output: CREATE TABLE SQL (PostgreSQL / Supabase)
//
// 개발자가 SQL을 손으로 쓰는 순간 공장이 아니다.
// 매니페스트 → SQL 자동 생성.
// ============================================================

import type { EntitySchemaMeta, FieldSchemaMeta, PluginManifest } from '../core/boundary';

// --- Core 필수 컬럼 (모든 테이블에 자동 추가) ---
const CORE_COLUMNS: FieldSchemaMeta[] = [
  { name: 'id', type: 'uuid', default: 'gen_random_uuid()' },
  { name: 'tenant_id', type: 'uuid', references: 'tenants(id)' },
  { name: 'created_at', type: 'timestamptz', default: 'now()' },
  { name: 'updated_at', type: 'timestamptz', default: 'now()' },
];

// --- 단일 테이블 DDL 생성 ---
function generateTableDDL(entity: EntitySchemaMeta): string {
  const allFields = [...entity.fields];

  // core 컬럼이 없으면 자동 추가
  const hasId = allFields.some((f) => f.name === 'id');
  if (!hasId) {
    allFields.unshift(...CORE_COLUMNS);
  }

  const columnDefs = allFields.map((field) => {
    let line = `  ${field.name} ${field.type.toUpperCase()}`;

    if (field.name === 'id') {
      line += ' PRIMARY KEY';
      if (field.default) line += ` DEFAULT ${field.default}`;
    } else {
      if (!field.nullable && field.name !== 'id') line += ' NOT NULL';
      if (field.default) line += ` DEFAULT ${field.default}`;
      if (field.references) line += ` REFERENCES ${field.references} ON DELETE CASCADE`;
    }

    return line;
  });

  // RLS 정책
  const rlsPolicy = `
ALTER TABLE ${entity.table} ENABLE ROW LEVEL SECURITY;
CREATE POLICY ${entity.table}_isolation ON ${entity.table}
  FOR ALL USING (tenant_id = current_tenant_id());`;

  // updated_at 트리거
  const trigger = `
CREATE TRIGGER trg_${entity.table}_updated BEFORE UPDATE ON ${entity.table}
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();`;

  // 인덱스
  const index = entity.filterable
    ? entity.filterable.map((f) =>
      `CREATE INDEX IF NOT EXISTS idx_${entity.table}_${f} ON ${entity.table}(tenant_id, ${f});`
    ).join('\n')
    : '';

  return `-- ${entity.label} (${entity.table})
CREATE TABLE IF NOT EXISTS ${entity.table} (
${columnDefs.join(',\n')}
);${rlsPolicy}${trigger}
${index}`;
}

// --- 전체 매니페스트 → 마이그레이션 SQL ---
export function generateMigration(manifests: PluginManifest[]): string {
  const tables: string[] = [];
  const seen = new Set<string>();

  for (const manifest of manifests) {
    for (const entity of manifest.entities) {
      if (seen.has(entity.table)) continue;
      seen.add(entity.table);
      tables.push(generateTableDDL(entity));
    }
  }

  return `-- ============================================================
-- Auto-Generated by Factory Compiler
-- DO NOT EDIT MANUALLY — regenerate with: npm run compile
-- Generated: ${new Date().toISOString()}
-- ============================================================

-- Ensure core function exists
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

${tables.join('\n\n')}
`;
}

// --- 단일 엔티티 DDL (CLI에서 즉시 실행용) ---
export function generateSingleTable(entity: EntitySchemaMeta): string {
  return generateTableDDL(entity);
}
