// ============================================================
// Factory Compiler — OpenAPI Generator
// Input:  EntitySchemaMeta[] + PluginManifest[]
// Output: OpenAPI 3.1 Specification (JSON)
//
// 매니페스트만 있으면 API 명세가 자동 생성됨.
// 외부 개발자가 API를 사용할 수 있음.
// ============================================================

import type { EntitySchemaMeta, FieldSchemaMeta, PluginManifest } from '../core/boundary';

// --- 필드 타입 → OpenAPI 타입 ---
function toOpenApiType(type: string): { type: string; format?: string } {
  switch (type) {
    case 'text': return { type: 'string' };
    case 'numeric': return { type: 'number' };
    case 'boolean': return { type: 'boolean' };
    case 'uuid': return { type: 'string', format: 'uuid' };
    case 'timestamptz': return { type: 'string', format: 'date-time' };
    case 'date': return { type: 'string', format: 'date' };
    case 'jsonb': return { type: 'object' };
    default: return { type: 'string' };
  }
}

// --- 엔티티 → OpenAPI Schema ---
function entityToSchema(entity: EntitySchemaMeta): object {
  const properties: Record<string, object> = {};
  const required: string[] = [];

  // Core 필드
  properties['id'] = { type: 'string', format: 'uuid', readOnly: true };
  properties['tenant_id'] = { type: 'string', format: 'uuid', readOnly: true };
  properties['created_at'] = { type: 'string', format: 'date-time', readOnly: true };
  properties['updated_at'] = { type: 'string', format: 'date-time', readOnly: true };

  // 엔티티 필드
  for (const field of entity.fields) {
    const { type, format } = toOpenApiType(field.type);
    const prop: Record<string, unknown> = { type };
    if (format) prop.format = format;
    if (field.nullable === false) prop.nullable = false;
    properties[field.name] = prop;

    if (entity.requiredFields?.includes(field.name)) {
      required.push(field.name);
    }
  }

  return {
    type: 'object',
    properties,
    required: required.length > 0 ? required : undefined,
  };
}

// --- 엔티티 → API 경로 ---
function entityToPaths(entity: EntitySchemaMeta, baseUrl: string): Record<string, object> {
  const basePath = `${baseUrl}/${entity.name}`;
  const itemPath = `${baseUrl}/${entity.name}/{id}`;
  const schemaRef = { $ref: `#/components/schemas/${entity.name}` };

  return {
    [basePath]: {
      get: {
        summary: `${entity.label} 목록 조회`,
        parameters: [
          { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
          { name: 'limit', in: 'query', schema: { type: 'integer', default: 50 } },
          ...(entity.filterable ?? []).map((f) => ({
            name: f, in: 'query', schema: { type: 'string' },
          })),
        ],
        responses: {
          '200': {
            description: '성공',
            content: { 'application/json': { schema: { type: 'object', properties: {
              data: { type: 'array', items: schemaRef },
              meta: { type: 'object' },
            } } } },
          },
          '403': { description: '권한 없음' },
        },
      },
      post: {
        summary: `${entity.label} 생성`,
        requestBody: {
          content: { 'application/json': { schema: schemaRef } },
        },
        responses: {
          '201': { description: '생성됨' },
          '400': { description: '검증 실패' },
          '422': { description: '비즈니스 규칙 위반' },
        },
      },
    },
    [itemPath]: {
      patch: {
        summary: `${entity.label} 수정`,
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        requestBody: { content: { 'application/json': { schema: schemaRef } } },
        responses: { '200': { description: '수정됨' }, '404': { description: '없음' } },
      },
      delete: {
        summary: `${entity.label} 삭제`,
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: { '204': { description: '삭제됨' }, '404': { description: '없음' } },
      },
    },
  };
}

// --- 전체 OpenAPI 생성 ---
export function generateOpenApi(manifests: PluginManifest[], baseUrl = '/api/v1'): string {
  const schemas: Record<string, object> = {};
  const paths: Record<string, object> = {};
  const tags: { name: string; description: string }[] = [];

  for (const manifest of manifests) {
    tags.push({ name: manifest.name, description: `${manifest.industry} 도메인` });

    for (const entity of manifest.entities) {
      schemas[entity.name] = entityToSchema(entity);
      Object.assign(paths, entityToPaths(entity, baseUrl));
    }
  }

  const spec = {
    openapi: '3.1.0',
    info: {
      title: 'Business OS API',
      version: '1.0.0',
      description: 'Auto-generated by Factory Compiler',
    },
    tags,
    paths,
    components: { schemas },
  };

  return JSON.stringify(spec, null, 2);
}
